soctrack/config/routes.rb
Rails.application.routes.draw do

  resources :flights
  resources :recoveries
  resources :events
  devise_for :users
  resources :critical_flights
  devise_scope :user do
    root :to => 'critical_flights#index'
  end

  post '/critical_flight/accept_recovery', to: 'critical_flights#acceptRecovery'
  post '/critical_flight/remove_recovery', to: 'critical_flights#removeRecovery'
  post '/critical_flight/add_recovery', to: 'critical_flights#addRecovery'
  post '/critical_flight/recovery_reaction', to: 'critical_flights#changeRecoveryReaction'
  post '/user/update_favorites', to: 'critical_flights#updateFavorites'
  get '/user',to:'critical_flights#getFavorites'
  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

soctrack/app/models/flight.rb
class Flight < ApplicationRecord
  has_many :recovery
end

soctrack/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all.select{|f| f.critical_flight_id==nil}
    if params.has_key?("tail")
      @flights = @flights.select {|flight| flight["tail"] == params["tail"] }
    end
    if params.has_key?("leg")
      @flights = @flights.select {|flight| flight["leg"] == params["leg"] }
    end
    if params.has_key?("arrival")
      @flights = @flights.select {|flight| flight["arrival"] == params["arrival"] }
    end
    if params.has_key?("departure")
      @flights = @flights.select {|flight| flight["departure"] == params["departure"] }
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end
  
  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:tail, :leg, :arrival, :departure, :etd)
    end
end

soctrack/app/helpers/flights_helper.rb
module FlightsHelper
end

soctrack/app/views/flights/_form.html.erb
<%= form_for(flight) do |f| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tail %>
    <%= f.text_field :tail %>
  </div>

  <div class="field">
    <%= f.label :leg %>
    <%= f.text_field :leg %>
  </div>

  <div class="field">
    <%= f.label :arrival %>
    <%= f.text_field :arrival %>
  </div>

  <div class="field">
    <%= f.label :departure %>
    <%= f.text_field :departure %>
  </div>

  <div class="field">
    <%= f.label :etd %>
    <%= f.datetime_select :etd %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

soctrack/app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

soctrack/app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Tail</th>
      <th>Leg</th>
      <th>Arrival</th>
      <th>Departure</th>
      <th>Etd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.tail %></td>
        <td><%= flight.leg %></td>
        <td><%= flight.arrival %></td>
        <td><%= flight.departure %></td>
        <td><%= flight.etd %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

soctrack/app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

soctrack/app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tail:</strong>
  <%= @flight.tail %>
</p>

<p>
  <strong>Leg:</strong>
  <%= @flight.leg %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @flight.arrival %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @flight.departure %>
</p>

<p>
  <strong>Etd:</strong>
  <%= @flight.etd %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>