soctrack/config/routes.rb
Rails.application.routes.draw do

  resources :flights
  resources :recoveries
  resources :events
  devise_for :users
  resources :critical_flights
  devise_scope :user do
    root :to => 'critical_flights#index'
  end

  post '/critical_flight/accept_recovery', to: 'critical_flights#acceptRecovery'
  post '/critical_flight/remove_recovery', to: 'critical_flights#removeRecovery'
  post '/critical_flight/add_recovery', to: 'critical_flights#addRecovery'
  post '/critical_flight/recovery_reaction', to: 'critical_flights#changeRecoveryReaction'
  post '/user/update_favorites', to: 'critical_flights#updateFavorites'
  get '/user',to:'critical_flights#getFavorites'
  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

soctrack/app/models/recovery.rb
class Recovery < ApplicationRecord
  belongs_to :flight
  belongs_to :critical_flight
end

soctrack/app/controllers/recoveries_controller.rb
class RecoveriesController < ApplicationController
  before_action :set_recovery, only: [:show, :edit, :update, :destroy]

  # GET /recoveries
  # GET /recoveries.json
  def index
    @recoveries = Recovery.all
    respond_to do |format|
      format.html
      format.json { render :json => @recoveries.to_json(:include => :flight) }
    end
  end

  # GET /recoveries/1
  # GET /recoveries/1.json
  def show
  end

  # GET /recoveries/new
  def new
    @recovery = Recovery.new
  end

  # GET /recoveries/1/edit
  def edit
  end

  # POST /recoveries
  # POST /recoveries.json
  def create
    @recovery = Recovery.new(recovery_params)

    respond_to do |format|
      if @recovery.save
        format.html { redirect_to @recovery, notice: 'Recovery was successfully created.' }
        format.json { render :show, status: :created, location: @recovery }
      else
        format.html { render :new }
        format.json { render json: @recovery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recoveries/1
  # PATCH/PUT /recoveries/1.json
  def update
    respond_to do |format|
      if @recovery.update(recovery_params)
        format.html { redirect_to @recovery, notice: 'Recovery was successfully updated.' }
        format.json { render :show, status: :ok, location: @recovery }
      else
        format.html { render :edit }
        format.json { render json: @recovery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recoveries/1
  # DELETE /recoveries/1.json
  def destroy
    @recovery.destroy
    respond_to do |format|
      format.html { redirect_to recoveries_url, notice: 'Recovery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recovery
      @recovery = Recovery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recovery_params
      params.require(:recovery).permit(:selected, :AB, :OS, :CS, :DX, :OPS, :MX, :ITP, :SC)
    end
end

soctrack/app/helpers/recoveries_helper.rb
module RecoveriesHelper
end

soctrack/app/views/recoveries/_form.html.erb
<%= form_for(recovery) do |f| %>
  <% if recovery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recovery.errors.count, "error") %> prohibited this recovery from being saved:</h2>

      <ul>
      <% recovery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tail %>
    <%= f.text_field :tail %>
  </div>

  <div class="field">
    <%= f.label :leg %>
    <%= f.text_field :leg %>
  </div>

  <div class="field">
    <%= f.label :selected %>
    <%= f.check_box :selected %>
  </div>

  <div class="field">
    <%= f.label :AB %>
    <%= f.number_field :AB %>
  </div>

  <div class="field">
    <%= f.label :OS %>
    <%= f.number_field :OS %>
  </div>

  <div class="field">
    <%= f.label :CS %>
    <%= f.number_field :CS %>
  </div>

  <div class="field">
    <%= f.label :DX %>
    <%= f.number_field :DX %>
  </div>

  <div class="field">
    <%= f.label :OPS %>
    <%= f.number_field :OPS %>
  </div>

  <div class="field">
    <%= f.label :MX %>
    <%= f.number_field :MX %>
  </div>

  <div class="field">
    <%= f.label :ITP %>
    <%= f.number_field :ITP %>
  </div>

  <div class="field">
    <%= f.label :SC %>
    <%= f.number_field :SC %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

soctrack/app/views/recoveries/edit.html.erb
<h1>Editing Recovery</h1>

<%= render 'form', recovery: @recovery %>

<%= link_to 'Show', @recovery %> |
<%= link_to 'Back', recoveries_path %>

soctrack/app/views/recoveries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recoveries</h1>

<table>
  <thead>
    <tr>
      <th>Tail</th>
      <th>Leg</th>
      <th>Selected</th>
      <th>Ab</th>
      <th>Os</th>
      <th>Cs</th>
      <th>Dx</th>
      <th>Ops</th>
      <th>Mx</th>
      <th>Itp</th>
      <th>Sc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recoveries.each do |recovery| %>
      <tr>
        <td><%= recovery.tail %></td>
        <td><%= recovery.leg %></td>
        <td><%= recovery.selected %></td>
        <td><%= recovery.AB %></td>
        <td><%= recovery.OS %></td>
        <td><%= recovery.CS %></td>
        <td><%= recovery.DX %></td>
        <td><%= recovery.OPS %></td>
        <td><%= recovery.MX %></td>
        <td><%= recovery.ITP %></td>
        <td><%= recovery.SC %></td>
        <td><%= link_to 'Show', recovery %></td>
        <td><%= link_to 'Edit', edit_recovery_path(recovery) %></td>
        <td><%= link_to 'Destroy', recovery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recovery', new_recovery_path %>

soctrack/app/views/recoveries/new.html.erb
<h1>New Recovery</h1>

<%= render 'form', recovery: @recovery %>

<%= link_to 'Back', recoveries_path %>

soctrack/app/views/recoveries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tail:</strong>
  <%= @recovery.tail %>
</p>

<p>
  <strong>Leg:</strong>
  <%= @recovery.leg %>
</p>

<p>
  <strong>Selected:</strong>
  <%= @recovery.selected %>
</p>

<p>
  <strong>Ab:</strong>
  <%= @recovery.AB %>
</p>

<p>
  <strong>Os:</strong>
  <%= @recovery.OS %>
</p>

<p>
  <strong>Cs:</strong>
  <%= @recovery.CS %>
</p>

<p>
  <strong>Dx:</strong>
  <%= @recovery.DX %>
</p>

<p>
  <strong>Ops:</strong>
  <%= @recovery.OPS %>
</p>

<p>
  <strong>Mx:</strong>
  <%= @recovery.MX %>
</p>

<p>
  <strong>Itp:</strong>
  <%= @recovery.ITP %>
</p>

<p>
  <strong>Sc:</strong>
  <%= @recovery.SC %>
</p>

<%= link_to 'Edit', edit_recovery_path(@recovery) %> |
<%= link_to 'Back', recoveries_path %>