soctrack/config/routes.rb
Rails.application.routes.draw do

  resources :flights
  resources :recoveries
  resources :events
  devise_for :users
  resources :critical_flights
  devise_scope :user do
    root :to => 'critical_flights#index'
  end

  post '/critical_flight/accept_recovery', to: 'critical_flights#acceptRecovery'
  post '/critical_flight/remove_recovery', to: 'critical_flights#removeRecovery'
  post '/critical_flight/add_recovery', to: 'critical_flights#addRecovery'
  post '/critical_flight/recovery_reaction', to: 'critical_flights#changeRecoveryReaction'
  post '/user/update_favorites', to: 'critical_flights#updateFavorites'
  get '/user',to:'critical_flights#getFavorites'
  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

soctrack/app/models/critical_flight.rb
class CriticalFlight < ApplicationRecord
  has_one :flight
  has_many :recovery
  serialize :event
end

soctrack/app/controllers/critical_flights_controller.rb
class CriticalFlightsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_critical_flight, only: [:show, :edit, :update, :destroy]

  # GET /critical_flights
  # GET /critical_flights.json
  def index
    @critical_flights = CriticalFlight.all
    puts "THIS IS THE TYPE OF ALL FLIGHTS"
    respond_to do |format|
      format.html
      format.json { render :json => @critical_flights.to_json(include: [{ :recovery => { :include => :flight }}, :flight]) }
    end
  end

  def getFavorites
    respond_to do |format|
      format.html
      format.json { render :json => current_user.to_json() }
    end
  end
  
  def updateFavorites
    cFlight = CriticalFlight.find(params[:critical_flight])
    favStatus = params[:favorite]
    if favStatus
     if current_user.favorite == nil
      current_user.favorite = []
      current_user.save
     end
     current_user.favorite.push(cFlight.id)
    else
     if current_user.favorite != nil
       current_user.favorite.delete_if {|f| f==cFlight.id}
     end
    end
    
    respond_to do |format|
      #if newRecovery.save
      
      #else
        
      #end
      return true
    end
  end


  def addRecovery
    cFlight = CriticalFlight.find(params[:critical_flight])
    newRecovery = Recovery.new
    newRecovery.flight_id = Flight.find_by_leg(params[:flight_leg].to_i).id

    newRecovery.critical_flight_id = params[:critical_flight]
    respond_to do |format|
      if newRecovery.save
        puts "new recovery saved"
        ActionCable.server.broadcast 'critical_flight_channel',
                content:  JSON.parse(newRecovery.to_json(include: :flight)),
                action: "addrecovery"
        head :ok
        return
      else
        puts "not saved"
        puts newRecovery.errors
        format.html { render json: newRecovery.errors, status: :unprocessable_entity}
        format.json { render json: newRecovery.errors, status: :unprocessable_entity }
        flash.now[:alert] = 'Error while adding recovery option!'
        return
      end
    end
  end

  def changeRecoveryReaction
    cFlight = CriticalFlight.find(params[:critical_flight])
    critical_flight_id = params[:critical_flight];
    recoveryid = params[:recovery]
    department = params[:department]
    reactionNumber = params[:recovery_reaction]
    returnHash = Hash["critical_flight_id" => critical_flight_id, "recovery_id" => recoveryid, "department" => department, "reaction_number" => reactionNumber];
    puts "STEP 1"
    cFlight.recovery.each{ |r|
      print "#{r.id} == #{recoveryid}"
      if(r.id.to_i == recoveryid.to_i)
        dRecovery = r
        dRecovery[department] = reactionNumber
        dRecovery.save
        puts "RECOVERy"
        puts dRecovery
        ActionCable.server.broadcast 'critical_flight_channel',
                                   content:  returnHash,
                                   action: "recoveryreaction"
        head :ok
      end
    }
  end

  def removeRecovery
    cFlight = CriticalFlight.find(params[:critical_flight])
    critical_flight_id = params[:critical_flight]
    recoveryid = params[:recovery]
    dRecovery = nil
    print "Recovery ID: #{recoveryid} ; CFlightID: #{params[:critical_flight]}"
    cFlight.recovery.each{ |r|
      if(r.id.to_i == recoveryid.to_i)
        dRecovery = r
        dRecovery.destroy
        returnHash = Hash["critical_flight_id" => critical_flight_id, "recovery_id" => recoveryid]

        # cFlight.recovery.delete(r.id)
        #
        # dRecovery.destroy
        print "RETURN HASH"
        puts returnHash
        cFlight.save
        ActionCable.server.broadcast 'critical_flight_channel',
                                   content:  returnHash,
                                   action: "removerecovery"
        head :ok
        return
      end
    }
  end

  def acceptRecovery
    cFlight = CriticalFlight.find(params[:critical_flight])
    critical_flight_id = params[:critical_flight]
    recoveryid = params[:recovery]
    dRecovery = nil
    print "Recovery ID: #{recoveryid} ; CFlightID: #{params[:critical_flight]}"
    removed_recovery = []
    cFlight.recovery.each{ |r|
      if(r.id.to_i == recoveryid.to_i)
        r.selected = true
        r.save
        cFlight.save
        returnHash = Hash["critical_flight_id" => critical_flight_id, "recovery_id" => recoveryid]
        ActionCable.server.broadcast 'critical_flight_channel',
                                   content:  returnHash,
                                   action: "acceptrecovery"
        head :ok
      end
    }
    return
  end

  # GET /critical_flights/1
  # GET /critical_flights/1.json
  def show
    @critical_flight = CriticalFlight.find(params[:id])
    puts @critical_flight.recovery
    # puts "THIS IS A MESSAGE"
    respond_to do |format|
      format.html
      format.json { render :json => @critical_flight.to_json(:include => :recovery) }
    end
  end

  # GET /critical_flights/new
  def new
    @critical_flight = CriticalFlight.new
  end

  # GET /critical_flights/1/edit
  def edit
  end

  # POST /critical_flights
  # POST /critical_flights.json
  def create
    puts critical_flight_params
    puts params.keys
    foundFlight = Flight.find_by_leg(params[:critical_flight][:flight_leg])
    puts "FLIGHT FOUND: "
    puts params[:critical_flight][:flight_leg]
    puts foundFlight
    # params.except(:password, :password_confirmation, :credit_card)
    # @critical_flight = CriticalFlight.new(params[:critical_flight].permit(:event))
    @critical_flight = CriticalFlight.new(critical_flight_params.except(:flight_leg, :authenticity_token))
    @critical_flight.event = params[:critical_flight][:event]
    respond_to do |format|
      @critical_flight.flight = foundFlight
      puts @critical_flight
      if @critical_flight.save
        puts "saved"
        flash.now[:notice] = 'Flight Saved'
        format.html { render :json => @critical_flights.to_json(include: [{ :recovery => { :include => :flight }}, :flight]) , status: :created}
        format.json { render :json => @critical_flights.to_json(include: [{ :recovery => { :include => :flight }}, :flight]) , status: :created}
        puts "about to broadcast"
        ActionCable.server.broadcast 'critical_flight_channel',
                                   content:  JSON.parse(@critical_flight.to_json(include: [{ :recovery => { :include => :flight }}, :flight])),
                                   action: "flightcreate"
              head :ok
        puts "finished broadcast"
      else
        puts "not saved"
        format.html { render :new }
        format.json { render json: @critical_flight.errors, status: :unprocessable_entity }
        flash.now[:alert] = 'Error while creating flight!'
      end
      puts "completes"
      return
    end
  end

  # PATCH/PUT /critical_flights/1
  # PATCH/PUT /critical_flights/1.json
  def update
    respond_to do |format|
      if @critical_flight.update(critical_flight_params)
        format.html { redirect_to @critical_flight, notice: 'Critical flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @critical_flight }
      else
        format.html { render :edit }
        format.json { render json: @critical_flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /critical_flights/1
  # DELETE /critical_flights/1.json
  def destroy
    @critical_flight.destroy
    respond_to do |format|
      format.html { redirect_to critical_flights_url, notice: 'Critical flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_critical_flight
      @critical_flight = CriticalFlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def critical_flight_params
      params.require(:critical_flight).permit(:event, :flight_leg, "event")
    end
end

soctrack/app/helpers/critical_flights_helper.rb
module CriticalFlightsHelper
end

soctrack/app/views/critical_flights/_form.html.erb
<%= form_for(critical_flight) do |f| %>
  <% if critical_flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(critical_flight.errors.count, "error") %> prohibited this critical_flight from being saved:</h2>

      <ul>
      <% critical_flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %>
    <%= f.text_area :event %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

soctrack/app/views/critical_flights/edit.html.erb
<h1>Editing Critical Flight</h1>

<%= render 'form', critical_flight: @critical_flight %>

<%= link_to 'Show', @critical_flight %> |
<%= link_to 'Back', critical_flights_path %>

soctrack/app/views/critical_flights/index.html.erb
<% @title = "Critical Flights" %>
<div id="updateTableAlertDiv" class="alert alert-info alert-dismissible hide" role="alert" class="hide">
  <a id="updateTableAlert" class="btn btn-xs btn-primary pull-right">Update</a>
  New Critical Flight added. Click Update to update table.
</div>
<div class="container-fluid">
  <div id="dashboardPane" class="col-md-9">
    <table id="flightsTable" class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th>Tail No.</th>
          <th>Leg ID</th>
          <th>Departure</th>
          <th>Arrival</th>
          <th>Event Types</th>
          <th>Recovery Options</th>
          <th>ETD</th>
          <th>Chat</th>
        </tr>
      </thead>
    </table>
  </div>
  <div id="chatPane" class="col-md-3">
    <div class="row">
      <div id="firechat-wrapper">
      </div>
    </div>
  </div>
</div>
  <div class="modal fade" id="addRecoveryModal" tabindex="-1" role="dialog" aria-labelledby="">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="createFlightModal">Add Recovery</h4>
          </div>
          <div class="modal-body">
              <form id="newFlightForm" class ="newFlightForm findFlightsForm">
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon">Tail No.</span>
                  <input class="form-control" placeholder="Enter Tail Number here" name="tail" type="text"/>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon">Leg ID</span>
                  <input class="form-control" placeholder="Enter Leg ID here" name="leg" type="text"/>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 col-xs-6 col-sm-6">
                  <div class="form-group"><div class="input-group">
                    <span class="input-group-addon">Departure</span>
                    <input class="form-control" placeholder="Enter Departure Airport Code" name="departure" type="text"/>
                  </div></div>
                </div>
                <div class="col-md-6 col-xs-6 col-sm-6">
                  <div class="form-group"><div class="input-group">
                    <span class="input-group-addon">Arrival</span>
                    <input class="form-control" placeholder="Enter Arrival Airport Code" name="arrival" type="text"/>
                  </div></div>
                </div>
              </div>
              <button type="button" class="findFlightsButton btn btn-success" >Find Flights</button>
              <div class="row">
                <table class="table table-striped flightsSelectTable">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Tail</th>
                      <th>Leg</th>
                      <th>Departure</th>
                      <th>Arrival</th>
                      <th>ETD</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
              </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" id="addRecoveryOptionCallButton"class="btn btn-primary">Add To Flight</button>
          </div>
        </div>
    </div>
  </div>

<!-- Modal -->
  <div class="modal fade" id="addFlightModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="createFlightModal">Create Flight</h4>
          </div>
          <div class="modal-body">
              <form id="newFlightForm" class ="findFlightsForm">
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon">Tail No.</span>
                  <input class="form-control" placeholder="Enter Tail Number here" name="tail" type="text"/>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon">Leg ID</span>
                  <input class="form-control" placeholder="Enter Leg ID here" name="leg" type="text"/>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 col-xs-6 col-sm-6">
                  <div class="form-group"><div class="input-group">
                    <span class="input-group-addon">Departure</span>
                    <input class="form-control" placeholder="Enter Departure Airport Code" name="departure" type="text"/>
                  </div></div>
                </div>
                <div class="col-md-6 col-xs-6 col-sm-6">
                  <div class="form-group"><div class="input-group">
                    <span class="input-group-addon">Arrival</span>
                    <input class="form-control" placeholder="Enter Arrival Airport Code" name="arrival" type="text"/>
                  </div></div>
                </div>
              </div>
              <button type="button" class="findFlightsButton btn btn-success" >Find Flights</button>
              <div class="row">
                <table class="table table-striped flightsSelectTable">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Tail</th>
                      <th>Leg</th>
                      <th>Departure</th>
                      <th>Arrival</th>
                      <th>ETD</th>
                    </tr>
                  </thead>
                  <tbody>

                  </tbody>
                </table>
              </div>
              </form>
              <select id="eventsSelector" class="selectpicker show-tick" multiple data-live-search="true" title="Choose Events">
                <% Event.find(1).event_hash.each do |type, vals| %>
                  <optgroup label="<%=type%>">
                    <% vals.each do |val| %>
                    <option><%=val%></option>
                    <%end%>
                  </optgroup>
                <%end%>
              </select>
              <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" id="criticalFlightFormButton"class="btn btn-primary">Create</button>
          </div>
        </div>
    </div>
  </div>

soctrack/app/views/critical_flights/new.html.erb
<h1>New Critical Flight</h1>

<%= render 'form', critical_flight: @critical_flight %>

<%= link_to 'Back', critical_flights_path %>

soctrack/app/views/critical_flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tail:</strong>
  <%= @critical_flight.tail %>
</p>

<p>
  <strong>Leg:</strong>
  <%= @critical_flight.leg %>
</p>

<p>
  <strong>Source:</strong>
  <%= @critical_flight.source %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @critical_flight.destination %>
</p>

<p>
  <strong>Event:</strong>
  <%= @critical_flight.event %>
</p>

<p>
  <strong>Etd:</strong>
  <%= @critical_flight.etd %>
</p>

<%= link_to 'Edit', edit_critical_flight_path(@critical_flight) %> |
<%= link_to 'Back', critical_flights_path %>